{
 "title": "Dashboard pfSense",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "gw.callfin.ltd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\"}-node_memory_free_bytes{instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_free_bytes{instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{fstype=\"ufs\",instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\",mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail{fstype=\"ufs\",instance=\"172.29.24.1:9100\",job=\"gw1.callfin.ltd\",mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(node_network_transmit_bytes{job=\"gw1.callfin.ltd\",device=~\"vmx.*\"}[5m])"
    },
    {
     "expr": "irate(node_network_receive_bytes{job=\"gw1.callfin.ltd\",device=~\"vmx.*\"}[5m])"
    }
   ]
  },
  { "title": "gw.holytopmedia.ltd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"gw1.holytop\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"gw1.holytop\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"gw1.holytop\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"gw1.holytop\"}-node_memory_free_bytes{job=\"gw1.holytop\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_free_bytes{job=\"gw1.holytop\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{job=\"gw1.holytop\",mountpoint=\"/\"}-node_filesystem_avail{job=\"gw1.holytop\",mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail{job=\"gw1.holytop\",mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(node_network_transmit_bytes{job=\"gw1.holytop\",device=~\"em.*\"}[5m])"
    },
    {
     "expr": "irate(node_network_receive_bytes{job=\"gw1.holytop\",device=~\"em.*\"}[5m])"
    }
   ]
  },
  { "title": "gw.aiel2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"gw1.aiel2\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"gw1.aiel2\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"gw1.aiel2\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"gw1.aiel2\"}-node_memory_free_bytes{job=\"gw1.aiel2\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_free_bytes{job=\"gw1.aiel2\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{fstype=\"ufs\",job=\"gw1.aiel2\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel2\",mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel2\",mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(node_network_transmit_bytes{job=\"gw1.aiel2\",device=~\"vmx.*\"}[5m])"
    },
    {
     "expr": "irate(node_network_receive_bytes{job=\"gw1.aiel2\",device=~\"vmx.*\"}[5m])"
    }
   ]
  },
  {
   "title": "gw.aiel1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"gw1.aiel1\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{job=\"gw1.aiel1\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{job=\"gw1.aiel1\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_size_bytes{job=\"gw1.aiel1\"}-node_memory_free_bytes{job=\"gw1.aiel1\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_free_bytes{job=\"gw1.aiel1\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "File System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size{fstype=\"ufs\",job=\"gw1.aiel1\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel1\",mountpoint=\"/\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel1\",mountpoint=\"/\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "-irate(node_network_transmit_bytes{job=\"gw1.aiel1\",device=~\"vmx.*\"}[5m])"
      },
      {
       "expr": "irate(node_network_receive_bytes{job=\"gw1.aiel1\",device=~\"vmx.*\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "gw.targaryan.marketing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"gw1.targaryen\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{job=\"gw1.targaryen\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{job=\"gw1.targaryen\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_size_bytes{job=\"gw1.targaryen\"}-node_memory_free_bytes{job=\"gw1.targaryen\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_free_bytes{job=\"gw1.targaryen\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "File System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size{fstype=\"ufs\",job=\"gw1.targaryen\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"gw1.targaryen\",mountpoint=\"/\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"gw1.targaryen\",mountpoint=\"/\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "-irate(node_network_transmit_bytes{job=\"gw1.targaryen\",device=~\"vmx.*\"}[5m])"
      },
      {
       "expr": "irate(node_network_receive_bytes{job=\"gw1.targaryen\",device=~\"vmx.*\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "gw.vantucapital.ltd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"gw1.vantucapital\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{job=\"gw1.vantucapital\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{job=\"gw1.vantucapital\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_size_bytes{job=\"gw1.vantucapital\"}-node_memory_free_bytes{job=\"gw1.vantucapital\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_free_bytes{job=\"gw1.vantucapital\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "File System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size{fstype=\"ufs\",job=\"gw1.vantucapital\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"gw1.vantucapital\",mountpoint=\"/\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"gw1.vantucapital\",mountpoint=\"/\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "-irate(node_network_transmit_bytes{job=\"gw1.vantucapital\",device=~\"vmx.*\"}[5m])"
      },
      {
       "expr": "irate(node_network_receive_bytes{job=\"gw1.vantucapital\",device=~\"vmx.*\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}