{
 "title": "Dashboard WWW",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "www.72option.com", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"www.72option.com\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"www.72option.com\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"www.72option.com\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"www.72option.com\"}-node_memory_free_bytes{job=\"www.72option.com\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_free_bytes{job=\"www.72option.com\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{fstype=\"ufs\",job=\"www.72option.com\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"www.72option.com\",mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"www.72option.com\",mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(node_network_transmit_bytes{job=\"www.72option.com\",device=~\"em.*\"}[5m])"
    },
    {
     "expr": "irate(node_network_receive_bytes{job=\"www.72option.com\",device=~\"em.*\"}[5m])"
    }
   ]
  },
  { "title": "www.mrwolf.solutions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"www.mrwolf.solutions\"}-node_memory_free_bytes{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_free_bytes{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{job=\"www.mrwolf.solutions\",mountpoint=\"/\"}-node_filesystem_avail{job=\"www.mrwolf.solutions\",mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail{job=\"www.mrwolf.solutions\",mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(node_network_transmit_bytes{job=\"www.mrwolf.solutions\",device=~\"vmx.*\"}[5m])"
    },
    {
     "expr": "irate(node_network_receive_bytes{job=\"www.mrwolf.solutions\",device=~\"vmx.*\"}[5m])"
    }
   ]
  },
  {
   "title": "www.cfsum.com",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"gw1.aiel2\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{job=\"gw1.aiel2\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{job=\"gw1.aiel2\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_size_bytes{job=\"gw1.aiel2\"}-node_memory_free_bytes{job=\"gw1.aiel2\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_free_bytes{job=\"gw1.aiel2\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "File System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size{fstype=\"ufs\",job=\"gw1.aiel2\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel2\",mountpoint=\"/\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel2\",mountpoint=\"/\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "-irate(node_network_transmit_bytes{job=\"gw1.aiel2\",device=~\"vmx.*\"}[5m])"
      },
      {
       "expr": "irate(node_network_receive_bytes{job=\"gw1.aiel2\",device=~\"vmx.*\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "www.roiteks.com",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"gw1.aiel1\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{job=\"gw1.aiel1\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{job=\"gw1.aiel1\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_size_bytes{job=\"gw1.aiel1\"}-node_memory_free_bytes{job=\"gw1.aiel1\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_free_bytes{job=\"gw1.aiel1\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "File System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size{fstype=\"ufs\",job=\"gw1.aiel1\",mountpoint=\"/\"}-node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel1\",mountpoint=\"/\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_avail{fstype=\"ufs\",job=\"gw1.aiel1\",mountpoint=\"/\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "-irate(node_network_transmit_bytes{job=\"gw1.aiel1\",device=~\"vmx.*\"}[5m])"
      },
      {
       "expr": "irate(node_network_receive_bytes{job=\"gw1.aiel1\",device=~\"vmx.*\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}