{
 "title": "Infrastructure",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "callfin_node", "label": "callfin_node", "query": "label_values(instance)" },
   { "name": "callfin_port", "label": "callfin_port", "query": "label_values(instance)" },
   { "name": "holytop_node", "label": "holytop_node", "query": "label_values(instance)" },
   { "name": "holytop_port", "label": "holytop_port", "query": "label_values(instance)" },
   { "name": "targaryen_node", "label": "targaryen_node", "query": "label_values(instance)" },
   { "name": "targaryen_port", "label": "targaryen_port", "query": "label_values(instance)" },
   { "name": "vantu_node", "label": "vantu_node", "query": "label_values(instance)" },
   { "name": "vantu_port", "label": "vantu_port", "query": "label_values(instance)" },
   { "name": "aiel2_node", "label": "aiel2_node", "query": "label_values(instance)" },
   { "name": "aiel2_port", "label": "aiel2_port", "query": "label_values(instance)" },
   { "name": "aiel1_node", "label": "aiel1_node", "query": "label_values(instance)" },
   { "name": "aiel1_port", "label": "aiel1_port", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "pfSense", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "172.29.24.1",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"gw1.callfin.ltd\"}/node_memory_size_bytes{job=\"gw1.callfin.ltd\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"gw1.callfin.ltd\",mountpoint=\"/\"}/node_filesystem_size{job=\"gw1.callfin.ltd\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.8
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"gw1.callfin.ltd\",device='vmx2'}",
     "legendFormat": "NW errors",
     "units": "Bps",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.20.1",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.holytop\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"gw1.holytop\"}/node_memory_size_bytes{job=\"gw1.holytop\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"gw1.holytop\",mountpoint=\"/\"}/node_filesystem_size{job=\"gw1.holytop\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.8
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"gw1.holytop\",device='em2'}",
     "legendFormat": "NW errors",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.19.1",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.aiel2\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"gw1.aiel2\"}/node_memory_size_bytes{job=\"gw1.aiel2\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"gw1.aiel2\",mountpoint=\"/\"}/node_filesystem_size{job=\"gw1.aiel2\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.8
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"gw1.aiel2\",device='vmx0'}",
     "legendFormat": "NW errors",
     "units": "Bps",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.16.1",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.aiel1\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"gw1.aiel1\"}/node_memory_size_bytes{job=\"gw1.aiel1\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"gw1.aiel1\",mountpoint=\"/\"}/node_filesystem_size{job=\"gw1.aiel1\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.8
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"gw1.aiel1\",device='vmx1'}",
     "legendFormat": "NW errors",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.18.1",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.vantucapital\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"gw1.vantucapital\"}/node_memory_size_bytes{job=\"gw1.vantucapital\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"gw1.vantucapital\",mountpoint=\"/\"}/node_filesystem_size{job=\"gw1.vantucapital\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.8
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"gw1.vantucapital\",device='vmx2'}",
     "legendFormat": "NW errors",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.17.1",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.targaryen\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"gw1.targaryen\"}/node_memory_size_bytes{job=\"gw1.targaryen\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"gw1.targaryen\",mountpoint=\"/\"}/node_filesystem_size{job=\"gw1.targaryen\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.8
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"gw1.targaryen\",device='vmx2'}",
     "legendFormat": "NW errors",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  { "title": "WWW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "172.29.18.14",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"www.cfsum.com\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"www.cfsum.com\"}/node_memory_size_bytes{job=\"www.cfsum.com\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.9,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"www.cfsum.com\",mountpoint=\"/\"}/node_filesystem_size{job=\"www.cfsum.com\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"www.cfsum.com\",device='ens192'}",
     "legendFormat": "NW errors",
     "units": "Bps",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.16.50",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"www.72option.com\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"www.72option.com\"}/node_memory_size_bytes{job=\"www.72option.com\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.9,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"www.72option.com\",mountpoint=\"/\"}/node_filesystem_size{job=\"www.72option.com\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"www.72option.com\",device='em0'}",
     "legendFormat": "NW errors",
     "units": "Bps",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.18.15",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"www.roiteks.com\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"www.roiteks.com\"}/node_memory_size_bytes{job=\"www.roiteks.com\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.9,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"www.roiteks.com\",mountpoint=\"/\"}/node_filesystem_size{job=\"www.roiteks.com\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"www.roiteks.com\",device='ens192'}",
     "legendFormat": "NW errors",
     "units": "Bps",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "172.29.17.5",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "System Load",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, Mb",
     "crit": 0.95,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_memory_free_bytes{job=\"www.mrwolf.solutions\"}/node_memory_size_bytes{job=\"www.mrwolf.solutions\"}",
     "legendFormat": "RAM, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "HDD, Mb",
     "crit": 0.9,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "1-node_filesystem_avail{job=\"www.mrwolf.solutions\",mountpoint=\"/\"}/node_filesystem_size{job=\"www.mrwolf.solutions\",mountpoint=\"/\"} ",
     "legendFormat": "HDD, Mb",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "NW traffic",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_network_transmit_errs{job=\"www.mrwolf.solutions\",device='vmx0'}",
     "legendFormat": "NW errors",
     "units": "Bps",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  { "title": "Zimbra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "172.29.25.5",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "System Load",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "HDD, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "Mail queue",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zimbra_stats",
     "query": "SELECT difference(mean(\"bounced\")) + difference(mean(\"deferred\")) + difference(mean(\"delivered\")) + difference(mean(\"discarded\")) + difference(mean(\"forwarded\")) + difference(mean(\"held\")) + difference(mean(\"received\")) + difference(mean(\"rejected\")) FROM \"zimbra_stats\" WHERE (\"host\" = 'mail.callfin.ltd') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deferred" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "alias": "Net error",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT last(\"err_out\") FROM \"net\" WHERE (\"host\" = 'mail.callfin.ltd') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Zextras Expire",
     "crit": -5,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "zextras",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": -10
    }
   ]
  },
  {
   "title": "172.29.22.70",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 90,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "System Load",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.holytopmedia.com" }
     ],
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.holytopmedia.com" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "HDD, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.holytopmedia.com" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "Mail queue",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zimbra_stats",
     "query": "SELECT difference(mean(\"bounced\")) + difference(mean(\"deferred\")) + difference(mean(\"delivered\")) + difference(mean(\"discarded\")) + difference(mean(\"forwarded\")) + difference(mean(\"held\")) + difference(mean(\"received\")) + difference(mean(\"rejected\")) FROM \"zimbra_stats\" WHERE (\"host\" = 'mail.holytopmedia.com') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deferred" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "alias": "Net Error",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT last(\"err_out\") FROM \"net\" WHERE (\"host\" = 'mail.callfin.ltd') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.holytopmedia.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Zextras Expire",
     "crit": -5,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "zextras",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.holytopmedia.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": -10
    }
   ]
  },
  {
   "title": "172.29.19.4",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "System Load",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.cfsum.com" }
     ],
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.cfsum.com" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "HDD, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.cfsum.com" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "Mail queue",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zimbra_stats",
     "query": "SELECT mean(\"bounced\") +  mean(\"deferred\") + mean(\"delivered\") + mean(\"discarded\") + mean(\"forwarded\") + mean(\"held\") + mean(\"received\") FROM \"zimbra_stats\" WHERE (\"host\" = 'mail.cfsum.com') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "deferred" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "alias": "Net Error",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.cfsum.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Zextras Expire",
     "crit": -5,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "zextras",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.cfsum.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": -10
    }
   ]
  },
  {
   "title": "172.29.16.41",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "System Load",
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" = 'mail.aielmarketing.com') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.aielmarketing.com" }
     ],
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.aielmarketing.com" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "HDD, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.aielmarketing.com" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "Mail queue",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zimbra_stats",
     "query": "SELECT difference(mean(\"bounced\")) + difference(mean(\"deferred\")) + difference(mean(\"delivered\")) + difference(mean(\"discarded\")) + difference(mean(\"forwarded\")) + difference(mean(\"held\")) + difference(mean(\"received\")) + difference(mean(\"rejected\")) FROM \"zimbra_stats\" WHERE (\"host\" = 'mail.aielmarketing.com') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "deferred" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "alias": "Net Error",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.aielmarketing.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Zextras Expire",
     "crit": -5,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "zextras",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.aielmarketing.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": -10
    }
   ]
  },
  {
   "title": "172.29.18.40",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "System Load",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.vantucapital.ltd" }
     ],
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.vantucapital.ltd" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "HDD, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.vantucapital.ltd" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "Mail queue",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zimbra_stats",
     "query": "SELECT difference(mean(\"bounced\")) + difference(mean(\"deferred\")) + difference(mean(\"delivered\")) + difference(mean(\"discarded\")) + difference(mean(\"forwarded\")) + difference(mean(\"held\")) + difference(mean(\"received\")) + difference(mean(\"rejected\")) FROM \"zimbra_stats\" WHERE (\"host\" = 'mail.vantucapital.ltd') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deferred" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "alias": "Net Error",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.aielmarketing.com" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Zextras Expire",
     "crit": -5,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "zextras",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.vantucapital.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": -10
    }
   ]
  },
  {
   "title": "172.29.17.40",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "System Load",
     "crit": 0.95,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_load5{job=\"gw1.callfin.ltd\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "System Load",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.targaryen.marketing" }
     ],
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.75
    },
    {
     "aggregation": "Last",
     "alias": "RAM, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.targaryen.marketing" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "HDD, %",
     "crit": 90,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\") FROM \"disk\" WHERE (\"host\" = 'mail.targaryen.marketing') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.targaryen.marketing" }
     ],
     "units": "percent",
     "valueHandler": "Number Threshold",
     "warn": 80
    },
    {
     "aggregation": "Last",
     "alias": "Mail queue",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zimbra_stats",
     "query": "SELECT difference(mean(\"bounced\")) + difference(mean(\"deferred\")) + difference(mean(\"delivered\")) + difference(mean(\"discarded\")) + difference(mean(\"forwarded\")) + difference(mean(\"held\")) + difference(mean(\"received\")) + difference(mean(\"rejected\")) FROM \"zimbra_stats\" WHERE (\"host\" = 'mail.targaryen.marketing') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deferred" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.callfin.ltd" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    },
    {
     "aggregation": "Last",
     "alias": "Net Error",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.targaryen.marketing" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Zextras Expire",
     "crit": -5,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "zextras",
     "query": "SELECT \"value\" *-1 FROM \"zextras\" WHERE (\"host\" = 'mail.targaryen.marketing') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mail.targaryen.marketing" }
     ],
     "units": "short",
     "valueHandler": "Number Threshold",
     "warn": -10
    }
   ]
  },
  {
   "title": "ESXi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  }
 ]
}